### ISSUE TITLE
Tests fail if protobuf is already installed in default bazel python executable

### ISSUE THREAD

**Issue by davidtwomey** [pybind/pybind11_protobuf#25]
I am encountering different behaviour in trying to run tests depending on whether protobuf is already installed in the default python executable (in my case `/usr/bin/python3.8`). OS = Ubuntu 20

Any help would be much appreciated! Perhaps I am missing something obvious here.

### Without pre-existing protobuf py installation :ok: 

When running tests without any python protobuf library the `bazel run` command works fine.
(Although I cannot import the extension outside of bazel run.)

```shell
# Check no protobuf py installation
pip show protobuf
$-> WARNING: Package(s) not found: protobuf
```

```shell
git clone https://github.com/pybind/pybind11_protobuf
cd pybind11_protobuf
bazel run pybind11_protobuf/tests:wrapped_proto_module_test
```

Tests run and pass ok
```
Running tests under Python 3.8.10: /usr/bin/python3...`
Ran 20 tests in 0.011s
... 
OK
```

> (NOTE however that you cannot run the generated protobuf `test_pb2.py` file 
`python bazel-bin/pybind11_protobuf/tests/test_pb2.py`
> ```
> Traceback (most recent call last):
>  File "bazel-bin/pybind11_protobuf/tests/test_pb2.py", line 21, in <module>
>    create_key=_descriptor._internal_create_key,
> AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
> ```

### With protobuf pre-installed (default)  :x:

When I install protobuf via default pip installation before running the tests, I encounter a segmentation fault.

```shell
# Install protobuf
pip install protobuf
bazel clean
bazel run pybind11_protobuf/tests:wrapped_proto_module_test
```

Tests now fail with a Segmentation fault

```
Running tests under Python 3.8.10: /usr/bin/python3
[ RUN      ] FastProtoTest.test_call_with_none
[       OK ] FastProtoTest.test_call_with_none
[ RUN      ] FastProtoTest.test_call_with_str
[       OK ] FastProtoTest.test_call_with_str
[ RUN      ] FastProtoTest.test_equality
Fatal Python error: Segmentation fault

Current thread 0x00007fb44f774740 (most recent call first):
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_pybind11_protobuf/pybind11_protobuf/tests/wrapped_proto_module_test.py", line 76 in test_equality
  File "/usr/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/usr/lib/python3.8/unittest/case.py", line 676 in run
  File "/usr/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/usr/lib/python3.8/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.8/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.8/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.8/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.8/unittest/runner.py", line 176 in run
  File "/usr/lib/python3.8/unittest/main.py", line 271 in runTests
  File "/usr/lib/python3.8/unittest/main.py", line 101 in __init__
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/testing/absltest.py", line 2409 in _run_and_get_tests_result
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/testing/absltest.py", line 2438 in run_tests
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/testing/absltest.py", line 2122 in main_function
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/app.py", line 251 in _run_main
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/app.py", line 303 in run
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/testing/absltest.py", line 2124 in _run_in_app
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_absl_py/absl/testing/absltest.py", line 2007 in main
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_pybind11_protobuf/pybind11_protobuf/tests/wrapped_proto_module_test.py", line 88 in <module>

```

### With protobuf pre-installed (cpp_implementation build flag) :x: 

Another variant of protobuf installation where I specify a pip install option which forces it to fall back on a `setup.py` build.

```shell
# Remove previous version
pip uninstall protobuf
# Install protobuf
pip install protobuf==3.18 --install-option="--cpp_implementation"
# Check protobuf implementation
python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
$ -> cpp
```

```shell
bazel clean
bazel run pybind11_protobuf/tests:wrapped_proto_module_test
```
 **Tests fail**
```shell
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pybind11_protobuf/tests:wrapped_proto_module_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_pybind11_protobuf/pybind11_protobuf/tests/wrapped_proto_module_test.py", line 14, in <module>
    from pybind11_protobuf.tests import compare
  File "/home/dtwomey/.cache/bazel/_bazel_dtwomey/866346c0fc431ca03a19bd6a2c5a1c06/execroot/com_google_pybind11_protobuf/bazel-out/k8-fastbuild/bin/pybind11_protobuf/tests/wrapped_proto_module_test.runfiles/com_google_pybind11_protobuf/pybind11_protobuf/tests/compare.py", line 50, in <module>
    from google.protobuf import descriptor
  File "/home/dtwomey/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/dtwomey/.local/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat21FastFieldValuePrinter19PrintMessageContentERKNS0_7MessageEiibPNS1_17BaseTextGeneratorE
```

**Comment by laramiel** [comment]
I've made quite a lot of changes to the internals of pybind11_protobuf; perhaps you'd have time to try this out and tell me whether it's still an issue for you?

I suspect that the old use of PyProto_API caused this to fail, and now PyProto_API is not used unless the build explicitly requests it.

**Comment by davidtwomey** [comment]
@laramiel yes great this is working now against latest main branch. Thanks for the help - closing!
